- name: install development packages
  tags:
    - full-install
    - light-install
    - packages
  kewlfft.aur.aur:
    name:
      - wget
      - base-devel
      - nfs-utils
      - libsecret
      - openvpn
      - python-pip
      - net-tools
      - pkgfile
      - postgresql-libs
      - dbeaver
      - postman-bin
      - dashbinsh
      - unixodbc
      - azure-cli
      - code-insiders
      - baobab
      - dnsmasq
      - openssh
      - ntfs-3g
      - nfs-utils
    use: yay
    state: present
    update_cache: false
  ignore_errors: false
