- name: install nvidia gpu related gaming packages
  tags:
    - full-install
    - light-install
    - packages
  kewlfft.aur.aur:
    name:
      - wine
      - nvidia-dkms 
      - nvidia-utils 
      - lib32-nvidia-utils 
      - nvidia-settings 
      - vulkan-icd-loader 
      - lib32-vulkan-icd-loader
    use: yay
    state: latest
    update_cache: yes
  become: true

- name: install game stores
  tags:
    - full-install
    - light-install
    - packages
  kewlfft.aur.aur:
    name:
      - lutris
      - steam
    use: yay
    state: latest
    update_cache: yes
  become: true