---
- name: Install kubernetes packages
  tags:
    - full-install
    - kubernetes
  kewlfft.aur.aur:
    name:
      - kubectl
      - kubectx
      - kubens
      - helm
      - docker-machine
      - docker-machine-driver-kvm2
      - minikube
      - lens
    use: yay
    state: present
    update_cache: false
  become: true