- name: make qtile config folder
  tags:
    - full-install
    - users
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/qtile"
    recurse: yes
    state: directory

- name: copy qtile files
  tags:
    - full-install
    - users
  copy: src={{ item.src }} dest={{ item.dest }}

  with_items:
    - {
        src: "qtile/autostart.sh",
        dest: "{{ lookup('env', 'HOME') }}/.config/qtile/autostart.sh",
        mode: 755,
      }
    - {
        src: "qtile/config.py",
        dest: "{{ lookup('env', 'HOME') }}/.config/qtile/config.py",
      }

- name: make fish config folder
  tags:
    - full-install
    - users
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/fish"
    recurse: yes
    state: directory

- name: copy fish files
  tags:
    - full-install
    - users
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: "fish/ftc.fish", dest: "/usr/share/doc/find-the-command/ftc.fish" }
    - {
        src: "fish/config.fish",
        dest: "{{ lookup('env', 'HOME') }}/.config/fish/config.fish",
      }
    - {
        src: "fish/fish_variables",
        dest: "{{ lookup('env', 'HOME') }}/.config/fish/fish_variables",
      }

- name: make kitty config folder
  tags:
    - full-install
    - users
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/kitty"
    recurse: yes
    state: directory

- name: copy kitty files
  tags:
    - full-install
    - users
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {
        src: "kitty/diff.conf",
        dest: "{{ lookup('env', 'HOME') }}/.config/kitty/diff.conf",
      }
    - {
        src: "kitty/dracula.conf",
        dest: "{{ lookup('env', 'HOME') }}/.config/kitty/dracula.conf",
      }
    - {
        src: "kitty/kitty.conf",
        dest: "{{ lookup('env', 'HOME') }}/.config/kitty/kitty.conf",
      }

- name: make flameshot config folder
  tags:
    - full-install
    - users
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/flameshot"
    recurse: yes
    state: directory

- name: copy flameshot files
  tags:
    - full-install
    - users
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {
        src: "flameshot/flameshot.ini",
        dest: "{{ lookup('env', 'HOME') }}/.config/flameshot/flameshot.ini",
      }

- name: make btop config folder
  tags:
    - full-install
    - users
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/btop/themes"
    recurse: yes
    state: directory

- name: copy btop files
  tags:
    - full-install
    - users
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {
        src: "btop/themes/dracula.theme",
        dest: "{{ lookup('env', 'HOME') }}/.config/btop/themes/dracula.theme",
      }
    - {
        src: "btop/btop.conf",
        dest: "{{ lookup('env', 'HOME') }}/.config/btop/btop.conf",
      }

- name: make dunst config folder
  tags:
    - full-install
    - users
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/dunst"
    recurse: yes
    state: directory

- name: copy dunst files
  tags:
    - full-install
    - users
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {
        src: "dunst/dunstrc",
        dest: "{{ lookup('env', 'HOME') }}/.config/dunst/dunstrc",
        mode: 755,
      }

- name: make rofi config folder
  tags:
    - full-install
    - users
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/rofi"
    recurse: yes
    state: directory

- name: copy rofi files
  tags:
    - full-install
    - users
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {
        src: "rofi",
        dest: "{{ lookup('env', 'HOME') }}/.config/rofi",
        mode: 755,
      }

- name: make bin config folder
  tags:
    - full-install
    - users
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    recurse: yes
    state: directory

- name: copy bin files
  tags:
    - full-install
    - users
  copy: src={{ item.src }} dest={{ item.dest }}

  with_items:
    - { src: "bin", dest: "{{ lookup('env', 'HOME') }}/.local/rofi", mode: 755 }

- name: make gtk-3.0 config folder
  tags:
    - full-install
    - users
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/gtk-3.0"
    recurse: yes
    state: directory

- name: copy gtk-3.0 files
  tags:
    - full-install
    - users
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {
        src: "gtk-3.0/settings.ini",
        dest: "{{ lookup('env', 'HOME') }}/.config/gtk-3.0/settings.ini",
      }

- name: make user Wallpaper folder
  tags:
    - full-install
    - users
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/wallpapers"
    recurse: yes
    state: directory

- name: copy user Wallpaper files
  tags:
    - full-install
    - users
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {
        src: "wallpapers/wallpaper.png",
        dest: "{{ lookup('env', 'HOME') }}/.config/wallpapers/wallpaper.png",
      }

- name: make system Wallpaper folder
  tags:
    - full-install
    - users
  become: True
  file:
    path: "/usr/share/wallpapers"
    recurse: yes
    state: directory

- name: copy system Wallpaper files
  tags:
    - full-install
    - users
  become: True
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {
        src: "wallpapers/wallpaper.png",
        dest: "/usr/share/wallpapers/wallpaper.png",
      }
