- name: make ssh folder
  tags:
    - full-install
    - users
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    recurse: yes
    mode: 770
    state: directory

- name: copy ssh files
  tags:
    - full-install
    - users
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {
        src: "ssh/id_rsa",
        dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa",
        mode: 640,
      }
    - {
        src: "ssh/id_rsa.pub",
        dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub",
        mode: 640,
      }
    - {
        src: "ssh/id_ed25519",
        dest: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519",
        mode: 640,
      }
    - {
        src: "ssh/id_ed25519.pub",
        dest: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub",
        mode: 640,
      }
