- name: install packages and update cache
  tags:
    - full-install
    - light-install
    - packages
  kewlfft.aur.aur:
    name:
      - wget
      - base-devel
      - flameshot
      - nfs-utils
      - cups
      - hplip
      - ghostscript
      - gsfonts
      - libcups
      - libsecret
      - openvpn
      - discord
      - python-pip
      - net-tools
      - pkgfile
      - kubectx
      - postgresql-libs
      - fish
      - kitty
      - fzf
      - bat
      - exa
      - brave-bin
      - uim
      - authy
      - dashbinsh
      - unixodbc
      - teams
      - find-the-command
      - ttf-meslo-nerd-font-powerlevel10k
      - blueman
      - arc-gtk-theme
      - vimix-cursors
      - tela-circle-icon-theme-git
      #- nerd-fonts-fira-code
      - arc-gtk-theme
      - arc-icon-theme
      - file-roller
      - nemo-fileroller
      - gparted
      - pavucontrol
      - baobab
      - xreader
      - unzip
      - unrar
      - p7zip
      - unarchiver
      - nano
      - neofetch
      - btop
      - nvtop
      - onlyoffice-bin
    use: yay
    state: present
    update_cache: yes
  ignore_errors: false
