- name: install packages and update cache
  tags:
    - full-install
    - light-install
    - packages
  kewlfft.aur.aur:
    name:
      - wget
      - base-devel
      - flameshot
      - nfs-utils
      - cups
      - hplip
      - ghostscript
      - gsfonts
      - libcups
      - libsecret
      - openvpn
      - discord
      - python-pip
      - net-tools
      - pkgfile
      - kubectx
      - postgresql-libs
      - fish
      - kitty
      - fzf
      - bat
      - exa
      - brave-bin
      - uim
      - authy
      - dashbinsh
      - unixodbc
      #- azure-cli
      #- spotify
      - teams
      - find-the-command
      - ttf-meslo-nerd-font-powerlevel10k
      - blueman
      - arc-gtk-theme
      - vimix-cursors
      - tela-circle-icon-theme-git
      - nerd-fonts-fira-code
      - code-insiders
      - pavucontrol
      - gnome-ssh-askpass3
      - systemd-ssh-agent
      - alsa-utils
      - pulseaudio
      - pulseaudio-alsa
      - pipewire-alsa
      - gst-libav
      - gst-plugins-ugly
      - gst-plugins-bad
      - system-config-printer
      - arc-gtk-theme
      - arc-icon-theme
      - file-roller
      - nemo-fileroller
      - gparted
      - pavucontrol
      - baobab
      - xreader
      - qemu-base
      - libvirt
      - iptables-nft
      - dnsmasq
      - virt-manager
      - virt-viewer
      - bridge-utils
      - dmidecode
      - edk2-ovmf
      - dhclient
      - dialog
      - wpa_supplicant
      - wireless_tools
      - netctl
      - inetutils
      - openssh
      - ntfs-3g
      - nfs-utils
      - e2fsprogs
      - smartmontools
      - btrfs-progs
      - gvfs
      - gvfs-smb
      - unzip
      - unrar
      - p7zip
      - unarchiver
      - nano
      - neofetch
      - btop
      - nvtop
      - onlyoffice-bin
    use: yay
    state: present
    update_cache: yes
  ignore_errors: false
